// Generated by gencpp from file vulcan_mavros/AddTwoInts.msg
// DO NOT EDIT!


#ifndef VULCAN_MAVROS_MESSAGE_ADDTWOINTS_H
#define VULCAN_MAVROS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <vulcan_mavros/AddTwoIntsRequest.h>
#include <vulcan_mavros/AddTwoIntsResponse.h>


namespace vulcan_mavros
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace vulcan_mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vulcan_mavros::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::vulcan_mavros::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::vulcan_mavros::AddTwoInts > {
  static const char* value()
  {
    return "vulcan_mavros/AddTwoInts";
  }

  static const char* value(const ::vulcan_mavros::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::vulcan_mavros::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::vulcan_mavros::AddTwoInts > 
template<>
struct MD5Sum< ::vulcan_mavros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vulcan_mavros::AddTwoInts >::value();
  }
  static const char* value(const ::vulcan_mavros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vulcan_mavros::AddTwoIntsRequest> should match 
// service_traits::DataType< ::vulcan_mavros::AddTwoInts > 
template<>
struct DataType< ::vulcan_mavros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::vulcan_mavros::AddTwoInts >::value();
  }
  static const char* value(const ::vulcan_mavros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vulcan_mavros::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::vulcan_mavros::AddTwoInts > 
template<>
struct MD5Sum< ::vulcan_mavros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vulcan_mavros::AddTwoInts >::value();
  }
  static const char* value(const ::vulcan_mavros::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vulcan_mavros::AddTwoIntsResponse> should match 
// service_traits::DataType< ::vulcan_mavros::AddTwoInts > 
template<>
struct DataType< ::vulcan_mavros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::vulcan_mavros::AddTwoInts >::value();
  }
  static const char* value(const ::vulcan_mavros::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VULCAN_MAVROS_MESSAGE_ADDTWOINTS_H
